### ISSUE TITLE
jsnap2py problems converting JSNAP test file to JSNAPy

### ISSUE THREAD

**Issue by gavmckee80** [Juniper/jsnapy#137]
jsnap2py -i network_checks.conf -o network_checks.yml
Traceback (most recent call last):
  File "/usr/local/bin/jsnap2py", line 86, in <module>
    data = test_case.parseString(content, parseAll=True).asList()
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1216, in parseString
    raise exc
pyparsing.ParseException: Expected end of text (at char 2600), (line:77, col:9)

do {
show_pim_interfaces;
mpls_interface;
mpls_lsp_extensive;
inet0_route_check;
check_show_interfaces_terse;
interface-ethernet-physical-extended;
check_bgp_summary;
}

mpls_interface {

	command show mpls interface;

	iterate mpls-interface {
	id interface-name;
		
	no-diff interface-name {
	info "Checking if there are changes in the name of the MPLS interfaces...";
	err " ERROR: the interface %s has changed its name from %s to %s.", $PRE/interface-name, $POST/interface-name;
	}

	no-diff mpls-interface-state {
	info "Checking the MPLS interface state ...";
	err " ERROR: the interface %s has changed its state from %s to %s.",$ID.1, $PRE/mpls-interface-state, $POST/mpls-interface-state;
	}

	list-not-less interface-name {
	info "Checking for missing MPLS interfaces ...";
	err " ERROR: the interface %s has gone missing.", $ID.1;
	}

	list-not-more interface-name {
	info "Checking for new MPLS interfaces ...";
	err " ERROR: the interface %s was not present before.", $ID.1;
	}
      }
}

mpls_lsp_extensive {
	command show mpls lsp extensive;

	iterate rsvp-session-data/rsvp-session/mpls-lsp {
	id ../../session-type;
	id name;
	
	no-diff destination-address {
	info "Checking if the LSP has changed its destination address ...";
	err " ERROR: the %s LSP %s has changed its destination address from %s to %s.", $ID.1, $ID.2, $PRE/destination-address, $POST/destination-address;
	}

	no-diff source-address {
	info "Checking if the LSP has changed its source address ...";
	err " ERROR: the %s LSP %s has changed its source address from %s to %s.", $ID.1, $ID.2, $PRE/source-address, $POST/source-address;
	}

	no-diff lsp-state {
	info "Checking if the LSP state has changed ...";
	err " ERROR: the %s LSP %s has changed its state from %s to %s.", $ID.1, $ID.2, $PRE/lsp-state, $POST/lsp-state;
	}

	no-diff name {
	info "Checking if the LSP name has changed ...";
	err " ERROR: the %s LSP %s has changed its name from %s to %s.", $ID.1, $ID.2, $PRE/name, $POST/name;
	}

	list-not-less name {
	info "Checking for missing LSPs ...";
	err " ERROR: the %s LSP %s has gone missing.", $ID.1, $ID.2;
	}

	list-not-more name {
	info "Checking for new LSPs ...";
	err " ERROR: the %s LSP %s was not present before.", $ID.1, $ID.2;
	}

	contains active-path, "(primary)" {
	info "Checking if the PRIMARY path is the active path for the LSP ...";
	err " ERROR: the %s LSP %s is not running on its PRIMARY path. It is currently running on %s.", $ID.1, $ID.2, $POST/active-path;
	}
     }
}

iterate rsvp-session-data {
	id session-type;
	
	no-diff count {
	info "Checking the number of LSPs ...";
	err " ERROR: the number of %s LSPs has changed from %s to %s.", $ID.1, $PRE/count, $POST/count;
	}

	no-diff up-count {
	info "Checking the number of LSP in UP state ...";
	err " ERROR: the number of %s LSPs in UP state has changed from %s to %s.", $ID.1, $PRE/up-count, $POST/up-count;
	}	

	no-diff down-count {
	info "Checking the number of LSP in DOWN state ...";
	err " ERROR: the number of %s LSPs in DOWN state has changed from %s to %s.", $ID.1, $PRE/down-count, $POST/down-count;
	}
    }

check_show_interfaces_terse {
	command show interfaces terse ge-*;
	
	iterate physical-interface {
	id ./name;
	
	no-diff oper-status {
	info "Checking PHY operational status of interfaces ...";
	err "	ERROR: the operational status for interface %s has changed from %s to %s.", $ID.1, $PRE/oper-status, $POST/oper-status;
	}

	no-diff admin-status {
	info "Checking PHY admin status of interfaces ...";
	err "	ERROR: the admin status for interface %s has changed from %s to %s.", $ID.1, $PRE/admin-status, $POST/admin-status;
	}

	list-not-less name {
	info "Checking for missing interfaces at PHY level ...";
	err "	ERROR: the interface %s is missing.", $ID.1;
	}

	list-not-more {
	info "Checking for new interfaces at PHY level ...";
	err "	ERROR: the interface %s is new.", $ID.1;
	}
}

	iterate physical-interface/logical-interface {
	id ./name;
	id ./address-family/address-family-name;
	id ./address-family/interface-address/ifa-local;
	
	no-diff oper-status {
	info "Checking LOGICAL operational status of interfaces ...";
	err "	ERROR: the operational status for interface %s has changed from %s to %s.", $ID.1, $PRE/oper-status, $POST/oper-status;
	}

	no-diff admin-status {
	info "Checking LOGICAL admin status of interfaces ...";
	err "	ERROR: the admin status of interface %s has changed from %s to %s.", $ID.1, $PRE/admin-status, $POST/admin-status;
	}

	list-not-less {
	info "Checking for missing interfaces at LOGICAL level ...";
	err "	ERROR: the interface %s is missing.", $ID.1;
	}

	list-not-more {
	info "Checking for new interfaces at LOGICAL level ...";
	err "	ERROR: the interface %s is new.", $ID.1;
	}

	no-diff address-family/address-family-name {
	info "Checking the address family configured in the interfaces ...";
	err "	ERROR: the address family for interface %s has changed from %s to %s.", $ID.1, $PRE/address-family/address-family-name, $POST/address-family/address-family-name;
	}

	list-not-less address-family/address-family-name {
	info "Checking for missing address family ...";
	err "	ERROR: the address family %s is missing on interface %s.",$ID.2, $ID.1;
	}

	list-not-more address-family/address-family-name {
	info "Checking for new family address ...";
	err "	ERROR: the address family %s has been added to the interface%s.", $ID.2, $ID.1;
	}

	no-diff address-family/interface-address/ifa-local {
	info "Checking the interface address configured under the interface...";
	err "	ERROR: the interface address for interface %s has changed from %s to %s.", $ID.1, $PRE/address-family/interface-address/ifa-local, $POST/address-family/interface-address/ifa-local;
	}

	list-not-less address-family/interface-address/ifa-local {
	info "Checking for missing interface address ...";
	err "	ERROR: the interface address %s has gone missing on interface %s.", $ID.3, $ID.1;
	}

	list-not-more address-family/interface-address/ifa-local {
	info "Checking for new interface address ...";
	err "	ERROR: the interface address %s has been added to the interface %s.", $ID.3, $ID.1;
	}
}
}

interface-ethernet-physical-extended {
        command show interface "[gxf]e-*" extensive;
        iterate physical-interface {
        id name;
                no-diff ./input-error-list/input-errors {
                        info Ethernet Interfaces - Input Errors Check;
                        err "Interface: %s input-errors changed from: %s to: %s since last snapshot", name, $PRE/./input-error-list/input-errors, $POST/./input-error-list/input-errors;
                }
                no-diff ./input-error-list/input-drops {
                        info Ethernet Interfaces - Input Drops Check;
                        err "Interface: %s input-drops changed from: %s to: %s since last snapshot", name, $PRE/./input-error-list/input-drops, $POST/./input-error-list/input-drops;
                }
                no-diff ./input-error-list/framing-errors {
                        info Ethernet Interfaces - Input Framing Errors Check;
                        err "Interface: %s framing-errors changed from: %s to: %s since last snapshot", name, $PRE/./input-error-list/framing-errors, $POST/./input-error-list/framing-errors;
                }
                no-diff ./input-error-list/input-runts {
                        info Ethernet Interfaces - Input Runts Check;
                        err "Interface: %s input-runts changed from: %s to: %s since last snapshot", name, $PRE/./input-error-list/input-runts, $POST/./input-error-list/input-runts;
                }
                no-diff ./input-error-list/input-fifo-errors {
                        info Ethernet Interfaces - Input FIFO Errors Check;
                err "Interface: %s input-fifo-errors changed from: %s to: %s since last snapshot", name, $PRE/./input-error-list/input-fifo-errors, $POST/./input-error-list/input-fifo-errors;
                }
                no-diff ./output-error-list/output-collisions {
                        info Ethernet Interfaces - Output Collisions Check;
                        err "Interface: %s output-collisions changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/output-collisions, $POST/./output-error-list/output-collisions;
                }
                no-diff ./output-error-list/output-drops {
                        info Ethernet Interfaces - Output Drops;
                        err "Interface: %s output-drops changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/output-drops, $POST/./output-error-list/output-drops;
                }
                no-diff ./output-error-list/aged-packets {
                        info Ethernet Interfaces - Output Aged Packets Check;
                        err "Interface: %s aged-packets changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/aged-packets, $POST/./output-error-list/aged-packets;
                }
                no-diff ./output-error-list/mtu-errors {
                        info Ethernet Interfaces - Output MTU Errors Check;
                        err "Interface: %s mtu-errors changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/mtu-errors, $POST/./output-error-list/mtu-errors;
                }
                no-diff ./output-error-list/hs-link-crc-errors {
                        info Ethernet Interfaces - Output hs-link-crc-errors Check;
                        err "Interface: %s hs-link-crc-errors changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/hs-link-crc-errors, $POST/./output-error-list/hs-link-crc-errors;
                }
                no-diff ./output-error-list/output-fifo-errors {
                        info Ethernet Interfaces - Output FIFO Errors Check;
                        err "Interface: %s output-fifo-errors changed from: %s to: %s since last snapshot", name, $PRE/./output-error-list/output-fifo-errors, $POST/./output-error-list/output-fifo-errors;
                }

        }
}

inet0_route_check {
	command show route;
	#checking the inet.0 routing table

	iterate /route-table/rt {
		id ./rt-destination;
		
		list-not-less {
		  info "Checking inet.0 for missing destinations";
		  err "Prefix missing: NET %s Next-Hop: %s Interface: %s", rt-destination, ./rt-entry/nh/to, ./rt-entry/nh/via;
		}

		list-not-more {
		  info "Checking inet.0 for new destinations";
		  err "New Prefix found: NET %s Next-Hop %s Interface: %s", rt-destination, ./rt-entry/nh/to, ./rt-entry/nh/via;
		}

	 }
	
}

check_bgp_summary {

	command show bgp summary;

	iterate . {
	
	no-diff group-count {
	info "Checking the number of BGP groups ...";
	err " ERROR: the number of BGP groups has changed from %s to %s.", $PRE/
	group-count, $POST/group-count;
	}

	no-diff peer-count {
	info "Checking the number of BGP peers ...";
	err " ERROR: the number of BGP peers has changed from %s to %s.", $PRE/peer-count, $POST/peer-count;
	}

	is-gt peer-count, 0 {
	info "Checking if the BGP configuration has at least 1 BGP peer configured...";
	err " ERROR: the BGP configuration does not have any peer configured!";
	}

	no-diff down-peer-count {
	info "Checking the number of BGP peers down ...";
	err " ERROR: the number of BGP peers down has changed from %s to %s.", $PRE/
	down-peer-count, $POST/down-peer-count;
	}
}

iterate bgp-peer/bgp-rib {
	id name;
	id ../peer-address;
	id ../peer-as;

	no-diff name {
	info "Checking if the BGP RIB name has changed ...";
	err " ERROR: the RIB %s of BGP peer %s (ASN %s) has changed from %s to %s.",$ID.1, $ID.2, $ID.3, $PRE/name, $POST/name;
	}

	list-not-less name {
	info "Checking for missing RIBs ...";
	err " ERROR: the RIB %s for the BGP peer %s (ASN %s) has gone missing.",$ID.1, $ID.2, $ID.3;
	}

	list-not-more name {
	info "Checking for new RIBs ...";
	err " ERROR: the RIB %s was not present before for the BGP peer %s (ASN%s).", $ID.1, $ID.2, $ID.3;
	}

	delta active-prefix-count, 20% {
	info "Checking if the number of BGP active prefix has changed more than 20%.";
	err " ERROR: the number of BGP active prefixes for RIB %s on the BGP peer %s(ASN %s) has changed more than 20 percent (before = %s / after = %s).", $ID.1, $ID.2, $ID.3, $PRE/active-prefix-count, $POST/active-prefix-count;
	}

	delta received-prefix-count, 20% {
	info "Checking if the number of BGP received prefix has changed more than 20%.";
	err " ERROR: the number of BGP received prefixes for RIB %s on the BGP peer %s (ASN %s) has changed more than 20 percent (before = %s / after = %s).", $ID.1, $ID.2, $ID.3, $PRE/received-prefix-count, $POST/received-prefix-count;
	}

	delta accepted-prefix-count, 20% {
	info "Checking if the number of BGP accepted prefix has changed more than 20%.";
	err " ERROR: the number of BGP accepted prefixes for RIB %s on the BGP peer %s (ASN %s) has changed more than 20 percent (before = %s / after = %s).", $ID.1, $ID.2, $ID.3, $PRE/accepted-prefix-count, $POST/accepted-prefix-count;
	}

	delta suppressed-prefix-count, 20% {
	info "Checking if the number of BGP suppressed prefix has changed more than 20%.";
	err " ERROR: the number of BGP suppressed prefixes for RIB %s on the BGP peer %s (ASN %s) has changed more than 20 percent (before = %s / after = %s).", $ID.1, $ID.2, $ID.3, $PRE/suppressed-prefix-count, $POST/suppressed-prefix-count;
	}
}

iterate bgp-peer {
	id peer-address;
	id peer-as;

	no-diff peer-address {
	info "Checking if the BGP peers addresses are still the same ...";
	err " ERROR: the BGP peer %s (ASN %s) has changed its address from %s to %s.", $ID.1, $ID.2, $PRE/peer-address, $POST/peer-address;
	}

	no-diff peer-as {
	info "Checking if the BGP peers ASNs are still the same ...";
	err " ERROR: the ASN for the BGP peer %s has changed from %s to %s.", $ID.1.$PRE/peer-asn, $POST/peer-asn;
	}

	no-diff flap-count {
	info "Checking if the BGP peer has flapped ...";
	err " ERROR: the BGP peer %s (ASN %s) has flapped.", $ID.1, $ID.2;
	}

	is-equal peer-state, "Established" {
	info "Checking if the BGP peers are in Established state ...";
	err " ERROR: the BGP peer %s (ASN %s) is not in Established state.", $ID.1,
	}
	
	}

}
}

show_pim_interfaces {

command show pim interfaces;

iterate pim-interfaces-information {
  id pim-interface-name;
  

  no-diff interface-name {
	info "Checking if there are changes in the name of the PIM interfaces...";
	err " ERROR: the interface %s has changed its name from %s to %s.",$ID.1 $PRE/pim-interface-name, $POST/pim-interface-name;
	}  

}

}

**Comment by gavmckee80** [comment]
Hi Guys,

Can anyone help with these conversion issues ?

**Comment by vnitinv** [comment]
@gavmckee80 I am looking into this.

**Comment by vnitinv** [comment]
Communicated over email
