### ISSUE TITLE
very slow printing of snapvalue contents returned by js.check

### ISSUE THREAD

**Issue by timamaryin** [Juniper/jsnapy#143]
While using module functions like this to make snapshots:

snapvalue = js.snap(config_file, "pre", dev=dev)
time.sleep(10)
print "Taking second snapshot"
snapvalue = js.snap(config_file, "post", dev=dev)
print "comparing data"
snapvalue = js.check(config_file, "pre", "post", dev=dev)

It takes 3-4 seconds to complete below for-loop:
I added time calls to measure:

print ("Time is " + time.strftime("%H:%M:%S",time.gmtime()) )
for snapcheck in snapvalue:
    print "\n -----------snapcheck----------"
    print "Tested on", snapcheck.device
    print "Final result: ", snapcheck.result
    print "Total passed: ", snapcheck.no_passed
    print "Total failed:", snapcheck.no_failed
    #pprint(dict(snapcheck.test_details))  
    #print snapcheck.test_results 
print ("Time is " + time.strftime("%H:%M:%S",time.gmtime()) )

Output:

Taking first snapshot
Taking snapshot of COMMAND: show interfaces terse ge*
Taking snapshot of RPC: get-bgp-summary-information
Taking second snapshot
Taking snapshot of COMMAND: show interfaces terse ge*
Taking snapshot of RPC: get-bgp-summary-information
comparing data
********************** Device: vega.csim-emea.jnpr.net **********************
Tests Included: test_command_version
********************* Command: show interfaces terse ge* *********************
PASS | All "oper-status" is same in pre and post snapshot [ 40 matched ]
********************** Device: vega.csim-emea.jnpr.net **********************
Tests Included: test_rpc_bgp
*************************RPC is get-bgp-summary-information*************************
BGP neighbor 192.168.1.107 is at different state !! it is ['Active'] was at ['Connect']
BGP neighbor 212.1.2.2 is at different state !! it is ['Active'] was at ['Connect']
BGP neighbor 192.168.1.103 is at different state !! it is ['Active'] was at ['Connect']
FAIL | All "peer-state" is not same in pre and post snapshot [ 35 matched / 3 failed ]
------------------------------- Final Result!! -------------------------------
Total No of tests passed: 1
Total No of tests failed: 1
Overall Tests failed!!!
Time is 08:50:36

 -----------snapcheck----------
Tested on vega.csim-emea.jnpr.net
Final result:  Failed
Total passed:  1
Total failed: 1
Time is 08:50:41

$ cat config_single_check.yml | grep -v "^#"
tests:
 - /home/tmaryin/jsnapy-tests/test_no_diff.yml
 - /home/tmaryin/jsnapy-tests/test_bgp_neighbor.yml

there are tests for 
get-bgp-summary-information
and show interfaces terse ge*

**Comment by maxdevyatov** [comment]
Looks similar to  [https://github.com/Juniper/jsnapy/issues/157](#157)
