### ISSUE TITLE
jsnap2py error

### ISSUE THREAD

**Issue by red1dz** [Juniper/jsnapy#146]
Could you please help me to fix the below issue, I am getting the same error even after updating jsnapy using Git.

#jsnap2py -i check -o check-migrated.yml
Traceback (most recent call last):
  File "/usr/bin/jsnap2py", line 84, in <module>
    data = test_case.parseString(content, parseAll=True).asList()
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1613, in parseString
    raise exc
pyparsing.ParseException: Expected end of text (at char 499), (line:29, col:6)

**Comment by dmontagner** [comment]
Hello,

Could you please upload check file ?

Please, do not use copy/paste, i.e., upload your original file.

Thanks

Sent from my iPhone

On 21 Aug 2016, at 20:51, red1dz <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please help me to fix the below issue, I am getting the same error even after updating jsnapy using Git.

#jsnap2py -i check -o check-migrated.yml
Traceback (most recent call last):
File "/usr/bin/jsnap2py", line 84, in
data = test_case.parseString(content, parseAll=True).asList()
File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1613, in parseString
raise exc
pyparsing.ParseException: Expected end of text (at char 499), (line:29, col:6)

-

**Comment by vnitinv** [comment]
It was resolved offline. Hence closing this issue.
