### ISSUE TITLE
High CPU utilization when executing multiple tests

### ISSUE THREAD

**Issue by maxdevyatov** [Juniper/jsnapy#157]
I see high CPU utilization when executing multiple snapcheck/check tests for multiple hosts. It takes very long time even to exit from JSNAP back to shell.

I was able to track down this to colorama.init(autoreset=True) call. It is called multiple times during execution.Things get worse with multiple tests/devices due to multiple initialization of class Operator variables where it calls colorama.init.

After I removed all calls of colorama.init(autoreset=True) from the code I don't see any performance issues anymore. 

Host OS: Ubuntu 16.04 VM.

**Comment by dmontagner** [comment]
Same problem here. Once I set the colorama.init to false, the problem went away.

I guess we could create an attribute on the SnapAdmin object that is set during the instantiation time.
