### ISSUE TITLE
--folder option for command line

### ISSUE THREAD

**Issue by vnitinv** [Juniper/jsnapy#171]
Can we have an option --folder so that we can provide this at run time to save snapshot at this given path and to read snapshots from this path itself.

say
```
jsnapy --snap pre -f myconf.yml --folder /var/tmp/jsnapy_snapshots 
```

**Comment by dmontagner** [comment]
Nitin,

what about the portable /etc/jsnapy/jsnapy.cfg ?

In theory, that would enable you to do something similar. Unless you want to change the snap_dir between snap collections. Then, the folder option you suggest will be better than the portable /etc/jsnapy/jsnapy.cfg.

The portable /etc/jsnapy/jsnapy.cfg is a must in a multi-user environment for JSNAPy.

Thanks

**Comment by eeishaan** [comment]
@vnitinv @dmontagner 
We have to decide between two possible solutions:
1. A cli option that permanently changes the lookup location for snapshots, testfiles and configuration files. In implementation this means modifying the configuration stored inside jsnapy.cfg. Here also we have to decide which jsnapy.cfg to modify - whether to modify the first jsnapy.cfg found in the newly defined [lookup hierarchy](https://github.com/Juniper/jsnapy/pull/179#issue-180506284) or the one present at /etc/jsnapy.
2. A cli option that changes lookup of testfiles, snaphshots and configuration files only once - during its execution only.

We can also provide both options though I doubt 2nd option would be useful.

**Comment by dmontagner** [comment]
Hi Ishaan,

IMO, option #2 is the more useful between the two. Bear in mind that option #2 must work for the module option too.

Thanks

Sent from my iPhone

On 3 Oct. 2016, at 17:31, Ishaan Kumar <notifications@github.com<mailto:notifications@github.com>> wrote:


@vnitinv<https://github.com/vnitinv> @dmontagner<https://github.com/dmontagner>
We have to decide between two possible solutions:
1. A cli option that permanently changes the lookup location for snapshots, testfiles and configuration files. In implementation this means modifying the configuration stored inside jsnapy.cfg. Here also we have to decide which jsnapy.cfg to modify - whether to modify the first jsnapy.cfg found in the newly defined lookup hierarchy<https://github.com/Juniper/jsnapy/pull/179#issue-180506284> or the one present at /etc/jsnapy.
2. A cli option that changes lookup of testfiles, snaphshots and configuration files only once - during its execution only.

We can also provide both options though I doubt 2nd option would be useful.

-
