### ISSUE TITLE
jsnapy SessionCloseError

### ISSUE THREAD

**Issue by larsb-nz** [Juniper/jsnapy#186]
Hi,
 
I have run into an issue with jsnapy and testing logical-system state.
 
When querying none LS information like interface and chassis operational info or configuration information, I don’t see this issue.
 
However, when using the following simplified test file configuration
 
get_ospf_interface:
  - rpc: get-ospf-interface-information
  - kwargs:
      logical-system: all
 
show_ospf_interface:
  - command: 'show ospf interface logical-system all'
 
the related snapshot file only holds the XML output tags.
 
<output> </output>
 
Looking at the debug information, the correct information about the LS is returned but not written to the snapshot file.
 
 
<<=====>>   XML response output removed to keep brief  <<=====>>  
</rpc-reply>
Delivering to <ncclient.operations.third_party.juniper.rpc.ExecuteRpc object at 0x7f00840c8d90>
Requesting 'CloseSession'
queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d4e4c39e-3479-416b-9ede-26b81f7e104d"><nc:close-session/></nc:rpc>
Sync request, will wait for timeout=30
Sending message
Sending: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d4e4c39e-3479-416b-9ede-26b81f7e104d"><nc:close-session/></nc:rpc>]]>]]>
[chan netconf-subsystem-0] EOF received (netconf-subsystem-0)
Selecting netconf:base:1.0 for encoding
[chan netconf-subsystem-0] EOF sent (netconf-subsystem-0)
parsing netconf v1.0
dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7f00840c8e10>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/15.1F6/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d4e4c39e-3479-416b-9ede-26b81f7e104d">
<ok/>
</rpc-reply>
Delivering to <ncclient.operations.session.CloseSession object at 0x7f008427f590>
**Broke out of main loop, error=SessionCloseError('Unexpected session close\nIN_BUFFER: `\n<!-- session end at 2016-11-08 12:44:01 UTC -->\n`',)
dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7f00840c8e10>**
EOF in transport thread
 
Any ideas?
 
test done on vMX, Junos: 15.1F6.9 with JSNAPy version: 1.0.1
 
thanks,
Lars

**Comment by vnitinv** [comment]
@larsb-nz the netconf log which you have posted from ncclient is just of CloseSession. So doesnt give any idea. Can you plese attach the netconf log from device. To configure netconf log on device please refer
http://www.juniper.net/documentation/en_US/junos14.2/topics/topic-map/netconf-traceoptions.html

**Comment by vnitinv** [comment]
@larsb-nz I am closing this issue. Please re-open if you feel this is related to JSNAPy only
