### ISSUE TITLE
Offline de-coupled JSNAPY

### ISSUE THREAD

**Issue by titusfoo** [Juniper/jsnapy#192]
Some environments make it hard to deploy things like python and packages or having script to talk to things directly

To realise some automation value I created a quick perl parser that parses CLI log from all |display xml that can be run offline that feeds into the snapshot repository

The CLI log can be from multiple nodes and line based parser takes care of figuring out current command (could be moved to XML parser to figure out what the rpc-reply was about sans hostname)

Before I convert this to python/jsnapy did somebody do something like this yet?

Also I guess there needs to be offline option or option to handle "use local repository only"

Examples could also use these single files and be used in tests to make sure intended example use cases will not break between releases offline

**Comment by ydnath** [comment]
@titusfoo You can run JSNAPy test cases on stored snapshots too. Am I missing something?

**Comment by eeishaan** [comment]
With the current jsnapy code on github you can run snapcheck command on stored snapshots as well using `--local` command. Refer here: #172

**Comment by titusfoo** [comment]
Yep missed the --local but still missing the offline ingest phase, 

I believe you would still need initially to run jsnapy with real connection unless you have some experience writing parsers and know the naming convention hidden in repository.

As far as I can see nothing that can parse for example CLI logs to catch all | display xml's for the --local

My question is more around if my CLI parser would fit into the project,

Also a test suite of jsnapy could use the examples associated with snapshot data to ensure no functionality breaks between releases and would motivate people to write more examples

**Comment by titusfoo** [comment]
My first bastardised catch-all CLI |display xml parser in perl was to parse 30 nodes CLI output from multiple show commands:
```
my $_currentNode;
my $_currentCommand;

my $_logfile = File::Slurp::read_file($_source_logfile);

my $xmlData = '';
my $currentXml;

foreach $_ (split(/\n/o, $_logfile)) {
    s/\r$//;

    # Expected shell can be tricky, move to XML-guess from rpc-reply
    if(/^[a-zA-Z0-9]{3,20}\@([A-Za-z0-9]+)>\s*(show\s .*)/oi) {
        $_currentNode = $1;
        my $_tryCmd = $2;
        if(defined($_tryCmd) && $_tryCmd =~ /^show/oi) {
            $_tryCmd =~ s/\s*\|.+//;
            $_currentCommand = lc($_tryCmd);
        }
    }
    elsif(/^<rpc-reply/o) {
        $currentXml = $_currentCommand;
    }

    if(defined($currentXml)) {
        $xmlData .= $_."\n";
    }

    if(/^<\/rpc-reply/o) {
        # FLUSH XML DATA out into repository
        $currentXml = undef;
        $xmlData = '';
    }    
}
```

The regexp matching hostname/current command is not ideal but it works for me.
xml-reply generally does not have host id associated with it :(

This way people can even use jsnapy with some logfile without directly hooking it into network or jumphost with often strict IT policy

**Comment by titusfoo** [comment]
I could also guess the current command from XML itself but then it will not know the current node leaving option to have the nodename as either command argument or part of a filename (CLI log limited to single node)

for example guessing show bgp neighbor w/ typical XML parser- 

```
   my $p = XML::LibXML->load_xml(<>);

    my $dom = XML::LibXML::XPathContext->new($p);

    # Who made the decision on including version in namespace URI's?! :)
    $dom->registerNs('junos','http://xml.juniper.net/junos/12.2R5/junos');
    $dom->registerNs('bgp', 'http://xml.juniper.net/junos/12.2R5/junos-routing');

    # Ignore namespace
    my $rpcReply = $p->firstChild();

    # Ignore namespace
    my $resp = $rpcReply->nonBlankChildNodes()->shift();

    # guesses.. rather foreach this as the element tagnames tend to stay static
    if(lc($resp->nodeName()) eq 'bgp-information') {

        # parsing based on guess, ignore namespaces
        for my $bgpPeerDOM ( $resp->findnodes( q{./*[name()="bgp-peer"]} ) ) {


```

**Comment by ydnath** [comment]
@titusfoo We should desist from screen scraping and related text processing, as a general use case. Junos provide a standards-based programmatic interface of XML-RPC over NETCONF/SSH. JSNAPy builds on top of the same support system.

**Comment by eeishaan** [comment]
@titusfoo What I understand from the above discussion is that:
1. You have an isolated box which jsnapy can't connect via NETCONF/SSH
2. But you still want to run Jsnapy on the box.
3. So you create a snapshot using perl parser of yours
4. Then jsnapy runs the various tests on that snapshot 

I  understand this may be useful as you may then go ahead and configure a cron job.

If this is correct, there are 2 issues with this scenario:
1. How will you load jsnapy onto the box? There is no pip or any other package manager.
2. Let's say you are able to load jsnapy onto the box. Then again, Pyez should be able to handle all your commands on the box itself, so there is no need to screen scrape the cli.

If this is incorrect, please explain your requirement by giving us a scenario

**Comment by titusfoo** [comment]
@ydnath Agreed, my world is just not perfect and I have to live in it. To avoid screenscraping I could always try get |save and copy of the box which is miles better and still would not require netconf and/or direct connectivity from jsnapy host and solves my concern as well

@eeishaan No issue with copying without direct connectivity the CLI log OR saved XML data separately to the isolated host/container that runs JSNAPY outside environment e.g. even on my laptop from captured data somebody else made I had no control of potentially sometime in long past

Since the "ingest to offline" part is solved without potentially having to write a script to process it, Thanks!

I would also like the thoughts on pairing examples with proper offline test data and maintaining repositories for data driven testing to ensure functionality on use-cases wise persists between releases outside basic unit testing?

e.g. I would like to sure the tool is maintained per use-cases and for this I would like to feed in examples with offline test data that could be tested automatically in isolation easily.
