### ISSUE TITLE
preceding-sibling' not found in prefix map

### ISSUE THREAD

**Issue by psagrera** [Juniper/jsnapy#207]
Hi, 

Given the following file : 

show_class-of-service_fabric_statistics:
- command: show class-of-service fabric statistics
- iterate:
    id: preceding-sibling::*[3], preceding-sibling::*[4]
    tests:
    - delta: drop-pps-high, 0
      err: '   ERROR: COS_STATUS: Drops in fabric plane, priority high, between source
        FPC{{id_0}} and destination FPC{{id_1}} have incremented: PRE:{{pre["drop-pps-high"]}}
        / POST: {{post["drop-pps-high"]}}'
      info: Checking fabric congestion in high priority queue
    - delta: drop-pps-low, 0
      err: '   ERROR: COS_STATUS: Drops in fabric plane, priority low, between source
        FPC{{id_0}} and destination FPC{{id_1}} have incremented: PRE:{{pre["drop-pps-high"]}}
        / POST: {{post["drop-pps-high"]}}'
      info: Checking fabric congestion in low priority queue
    xpath: //drop-statistics
tests_include:
- show_class-of-service_fabric_statistics

and the attached  xpath : 

I'm getting this error:

ERROR!! SyntaxError 
Complete Message: prefix 'preceding-sibling' not found in prefix map

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 699, in connect
    action)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 554, in get_test
    action)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 404, in compare_tests
    post_snap_file)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/check.py", line 644, in generate_test_files
    action)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/check.py", line 367, in compare_reply
    final_boolean_expr = self.expression_builder(testcases, None, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/check.py", line 254, in expression_builder
    last_test_instance = kwargs['op'].test_details[kwargs['teston']][-1]
IndexError: list index out of range

This xpath expression returns proper values in a xpath online tester for that xml:
//drop-statistics/preceding-sibling::*[3] 
//drop-statistics/preceding-sibling::*[4]

Could you help me to understand if I'm doing something or wrong or if I'm bumping into a bug.

Thanks in advance

**Comment by psagrera** [comment]
Attaching xpath .....
[xpath.txt](https://github.com/Juniper/jsnapy/files/661579/xpath.txt)

**Comment by ydnath** [comment]
@psagrera preceding-sibling is a relative operator. Please try specifying it in a specific context. eg: ```//drop-statistics/preceding-sibling::*```

**Comment by psagrera** [comment]
I'm getting the following error:

************** Command: show class-of-service fabric statistics
**************

-----------------------Performing delta Test
Operation-----------------------

ERROR!! SyntaxError

Complete Message: cannot use absolute path on element

ERROR!! IndexError

Complete Message:  list index out of range

show_class-of-service_fabric_statistics:
- command: show class-of-service fabric statistics
- iterate:
    *id: //drop-statistics/preceding-sibling::*[3],
//drop-statistics/preceding-sibling::*[4]*
    tests:
    - delta: drop-pps-high, 0
      err: '   ERROR: COS_STATUS: Drops in fabric plane, priority high,
between source
        FPC{{id_0}} and destination FPC{{id_1}} have incremented:
PRE:{{pre["drop-pps-high"]}}
        / POST: {{post["drop-pps-high"]}}'
      info: Checking fabric congestion in high priority queue
    - delta: drop-pps-low, 0
      err: '   ERROR: COS_STATUS: Drops in fabric plane, priority low,
between source
        FPC{{id_0}} and destination FPC{{id_1}} have incremented:
PRE:{{pre["drop-pps-high"]}}
        / POST: {{post["drop-pps-high"]}}'
      info: Checking fabric congestion in low priority queue
    xpath: //drop-statistics

Regards.



2016-12-19 17:39 GMT+01:00 Dwarakanath Yadavalli <notifications@github.com>:

**Comment by sidhujasminder** [comment]
@psagrera I will suggest you writing the test case in this format:
```
show_class-of-service_fabric_statistics:
  - command: show fabric
  - iterate:
      xpath: //fpc-queue-information
      id: dest-fpc-index, src-fpc-index
      tests:
        - delta: drop-statistics/drop-pps-high, 0
          err: ' ERROR: COS_STATUS: Drops in fabric plane, priority high, between source
          FPC{{id_0}} and destination FPC{{id_1}} have incremented: PRE:{{pre["drop-pps-high"]}}
          / POST: {{post["drop-pps-high"]}}'
          info: "Checking fabric congestion in high priority queue"
        - delta: drop-statistics/drop-pps-low, 0
          err: ' ERROR: COS_STATUS: Drops in fabric plane, priority low, between source
          FPC{{id_0}} and destination FPC{{id_1}} have incremented: PRE:{{pre["drop-pps-high"]}}
          / POST: {{post["drop-pps-high"]}}'
          info: "Checking fabric congestion in low priority queue"

```

But the thing in your testcase is that, for this current scenario there is no repeating element on which it can iterate. It can just be checked for one item. I am closing the issue for now, Please reopen if any doubts. Sorry for a very late response.
