### ISSUE TITLE
ConnectTimeoutError to device when removing passwd from main_configfile

### ISSUE THREAD

**Issue by red1dz** [Juniper/jsnapy#215]
Hello, 
For security reasons, we don't want to put the password in clear text in config file , so we want each user to use his own device credentials when using JSNAPy.
so when removed username and passwd arguments from yaml file , we are getting ConnectTimeoutError

Connecting to device Hostname................

Enter User name: username

Enter Password for username <username> : 
Connecting to device Hostname ................

ERROR occurred ConnectTimeoutError(Hostname)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 657, in connect
    post_snap)
  File "/usr/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 669, in connect
    raise Exception(ex)
Exception: ConnectTimeoutError(Hostname)

**Comment by eeishaan** [comment]
Please state which version you are using.
Please check whether netconf ssh in enabled on your device. You can run the following on the cli:
`show configuration system services`
This is how it looks for me:
```
r1_re> show configuration system services
netconf {
    ssh;
}
```

**Comment by vnitinv** [comment]
Hi @red1dz 
> For security reasons, we don't want to put the password in clear text in config file , so we want each user to use his own device credentials when using JSNAPy.

You can configure ssh key.

> so when removed username and passwd arguments from yaml file , we are getting ConnectTimeoutError
Does that mean when username/password provided in yaml fine, it works fine?

For debugging purpose, Can you enable netconf on device and share the netconf log.
I dont see issue wrt to username/password as that would give AuthenticationError. Connection Timeout error happens when Port or netconf is not configured properly. Share the device details. Also try with port as 22 in the yaml file.
```yaml
hosts:
  - device: xx.xx.xx.xx
    port: 22
```
