### ISSUE TITLE
jsnap2py: ID.1=id_0 and ID.2=id_1

### ISSUE THREAD

**Issue by nskalis** [Juniper/jsnapy#226]
Hi guys,

The jsnap2py utility does not rename the IDs correctly. More specifically,

in JSNAP $ID.1 is mapped to id_1 in jsnapy
in JSNAP $ID.2 is mapped to id_2 in snappy

how it should be according to the docs is:

in JSNAP $ID.1 should be id_0 in jsnapy
in JSNAP $ID.2 should be id_1 in snappy

**Comment by vnitinv** [comment]
@nskalis Nice catch 👍 
I will fix this.
