### ISSUE TITLE
Use kwargs while naming snapshots

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#233]
Refer #230.
This issue underlines a scenario where user is using the same rpc with different arguments. This leads to different snapshots. Due to the same rpc, the file name constructed to store both the snapshots is same. Hence contents of one of them is lost. We also have an optimization coming as part of #175 which gets impacted by this.
I would like to use this forum for discussion

**Comment by vnitinv** [comment]
@eeishaan we can use hash value of kwargs/args dictionary and append that to the snapshot file.

**Comment by jnpr-bowen** [comment]
I need this feature implemented as well. A simple example of repeated RPC call is ping, the file name constructed for all pings looks like:
device_snap_temp_ping.xml
If I need to test ping to 5 different hosts, jsnapy only keeps the results of the last test. 
I could help provide the fix, if someone can point me to where to look.

**Comment by sidhujasminder** [comment]
Fix #282
