### ISSUE TITLE
JSNAPy Logo

### ISSUE THREAD

**Issue by cg-cnu** [Juniper/jsnapy#235]
Hey guys,
In the similar lines of [PyEZ](https://github.com/Juniper/py-junos-eznc/issues/684) I have done a logo for this project as well.
![image](https://cloud.githubusercontent.com/assets/2767425/24075141/f1631dd0-0c3b-11e7-88e7-82bc07c45226.png)
The colors of ```JSNA``` represents ```Juniper``` and the ```Py``` colors represents python.
Would like to hear your comments.

**Comment by eeishaan** [comment]
@cg-cnu Wow! This looks nice! I think we should use the juniper font for the `JSNA` part

**Comment by cg-cnu** [comment]
@eeishaan If its ok to use, that would be awesome!

**Comment by eeishaan** [comment]
@cg-cnu Also, the logos you have made are all text based. Have you made some artwork too?
As jsnapy is built to help you avoid "Aw Snap!" situation, we can have a logo that conveys this meaning and as the word snap also appears in our product name we can sneak in some wordplay as well 😄

**Comment by cg-cnu** [comment]
>  we can sneak in some wordplay 
That sounds good! I will explore some ideas and get back!

**Comment by cg-cnu** [comment]
I put together all the logos we have done till now! 
![image](https://cloud.githubusercontent.com/assets/2767425/24078808/f3b23f64-0c9d-11e7-9013-87c114918eda.png)
The last one has a bit of word play with ```snap!```
If you like the direction we can explore a little more on it with fonts and colors.

**Comment by jessicagarrison** [comment]
Here is my prototype. 

![jsnapy](https://user-images.githubusercontent.com/15332231/28049603-47a64940-65ad-11e7-84e2-4d4a5e307d7a.png)

**Comment by jnpr-bowen** [comment]
The original logo is the 'cleanest' to me. I just have a hard time with the Juniper typeface N, but it is our typeface.
I like Jessica's prototype of artwork that ties in the idea of "take a picture", if that be done with the Juniper and Python color schemes, I think it could be a winner.

**Comment by dmontagner** [comment]
Here is my version built on top of @jessicagarrison idea.

![jsnapy-logo-draft](https://user-images.githubusercontent.com/4936154/28404797-1288c68e-6d6e-11e7-93ee-e8de53491d80.png)

**Comment by ydnath** [comment]
Logo is updated
