### ISSUE TITLE
Script execution stuck when one of device access failed.

### ISSUE THREAD

**Issue by stanley2k** [Juniper/jsnapy#244]
Hi Team,

I would like to share an issue when I am testing JSNAPy in my customer environment,need your recommendation, thanks!

Triggere condition:
1. Uses JSNAPy as a module in script
2. Multiple devices credentials in configuration file(This file keep device credentials and test file name), if there is only one device in configuration file and this issue will not trigger.
3. At least one test in configuration file
4. If one of device login failure due to telnet/ssh connection issue (IP unreachable, telnet or ssh does not enable...etc)
5. Script will stuck there and particular logs shown.
6. This issue can be seen although try/except is used in script

Below are my logs and partial codes:
`try:`
`snapvalue = js.snapcheck(device_audit_configuration_file_name, 'snap')`
#I though I am stuck in here, because I can see exception error logs “print get_local_time() + ‘: Error occurred: %s’ % error”

`except Exception as error:`
`print get_local_time() + ': Error occurred: %s' % error`
`sys.exit(0)`

First test with only one device in configuration file:

$ python phc_network_auditor.py device_test_config.yml 
#At this test, there is only one device entry in device_test_config.yml, which is 10.193.200.48

2017-05-04 15:33:52: Product health check begin running to check devices
Connecting to device 10.193.200.48 ................

ERROR occurred open_fail: port not ready
2017-05-04 15:34:00: Error occurred: open_fail: port not ready 

stanley@server:~/$ 
#Although this connection is failed to open, the script will not be stuck here, it will return to shell as normal.

Second test with 2 devices in configuration file:

stanley@server:~/$ python phc_network_auditor.py device_test_config.yml 
#At this test, there are two devices entry in device_test_config.yml, 10.193.200.48 and 10.193.200.49

2017-05-04 15:34:42: Product health check begin running to check devices
Connecting to device 10.193.200.48 ................

ERROR occurred open_fail: port not ready
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 665, in connect
    raise Exception(ex)
Exception: open_fail: port not ready

^C
#In the end up, it is stucked

Need recommendation here, thanks for your help!

Stanley Hsu

**Comment by vnitinv** [comment]
taken care via #256
