### ISSUE TITLE
Issues with obtaining "at least 1" test results

### ISSUE THREAD

**Issue by itsgc** [Juniper/jsnapy#301]
Hello,

I am trying to write a test case that iterates through all routing-instances we have in our config and validates that _all_ of them have a specific dhcp relay server configured.

If i have 8 routing instances, 3 of which are missing that server, i expect to get 3 errors and 5 passes. Instead, i get 21 errors and 5 passes because it counts 1 error per each "address" node that exists.

However, it seems there is no way i can check for "exist" of a given node only if it has a specific value.

if i check for "contains" it will check every single address node in forwarding-options/dhcp-relay/server-group/server-group and fail all those that do not match (this is not desired, we are ok with other dhcp relay servers being configured but _at least_ the one featured in the test should be there).

in short: i believe contains is not behaving as expected. rather than being happy with the first result, it keeps iterating and basically behaves like "is-equal".

This is basically my first attempt at writing a test case so i'm unsure if i'm just not using the correct depth to iterate on or the wrong test operator.

Any help would be appreciated.

test: 
---
test_applications:
    - rpc: get-config
    - kwargs:
        filter_xml: configuration/routing-instances
    - iterate:
        id: name
        xpath: //instance/forwarding-options/dhcp-relay/server-group
        tests:
            - contains: server-group/address/name, XX.YYY.YY.XX
              info: "Test Succeeded!! something exists for {{id_0}}"
              err: "Test Failed!!!"

Test output:
Tests Included : test_applications
Taking snapshot of RPC: get-config
********************* Device: ldncrt1.corp.yelpcorp.com *********************
Tests Included: test_applications
*************************RPC is get-config*************************
----------------------Performing contains Test Operation----------------------
Test Failed!!!
Test Failed!!!
Test Succeeded!! XX.YYY.YY.XX exists for vrf1
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Succeeded!! XX.YYY.YY.XX exists for vrf2
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Succeeded!! XX.YYY.YY.XX exists for vrf3
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Succeeded!! XX.YYY.YY.XX exists for vrf4
Test Failed!!!
Test Failed!!!
Test Failed!!!
Test Succeeded!! XX.YYY.YY.XX exists for vrf5
Test Failed!!!
FAIL | All "server-group/address/name" do not contains XX.YYY.YY.XX" [ 5 matched / 21 failed ]
------------------------------- Final Result!! -------------------------------
test_applications : Failed
Total No of tests passed: 0
Total No of tests failed: 1
Overall Tests failed!!!

**Comment by sidhujasminder** [comment]
@itsgc , i need a little information. Can you help me reproduce this one. I need to check the xml being generated for this rpc on your box. Once we see the xml, we can debug your test case.

 As a quick try seeing the testcase, can you change your testcase to the following:

```
test_applications:
- rpc: get-config
- kwargs:
filter_xml: configuration/routing-instances
- iterate:
id: name
xpath: //instance/forwarding-options/dhcp-relay/server-group
tests:
- contains: address/name, XX.YYY.YY.XX
info: "Test Succeeded!! something exists for {{id_0}}"
err: "Test Failed!!!"
```

PS: Xpath will be used as a base, in your case: //instance/forwarding-options/dhcp-relay/server-group will be used as a node. And all other nodes are with respect to this, the ` id: name` should be available in this node.

**Comment by sidhujasminder** [comment]
@itsgc can you provide the required information?

**Comment by itsgc** [comment]
Hello @sidhujasminder.
I run the test requested and also collected all the information i believe relevant. We are running this against a EX4300 VC running JunOS 14.1X53

Your test fails with a path not found because you are omitting "server-group" the second time.

This is the xml we are checking against:
            <forwarding-options>
                <dhcp-relay>
                    <server-group>
                        <server-group>
                            <name>ldn</name>
                            <address>
                                <name>172.16.25.2</name>
                            </address>
                            <address>
                                <name>172.16.25.3</name>
                            </address>
                            <address>
                                <name>172.18.32.10</name>
                            </address>
                            <address>
                                <name>172.17.32.10</name>
                            </address>
                        </server-group>
                    </server-group>

as you can see the server-group tag is repeated twice, one nested within the other.

Additionally, using id: name instead of id:../../../name will expand {{id_0}} into the name property **of the address node.** This is not what we want

What we care about is erroring **for each routing instance** and that's why we use ../../../name (which expands to the name property of the current <instance> node the iteration has got to)

- Here is the complete snapshot we are testing against: [jsnapy_rpc_snapshot_20180306.xml.txt](https://github.com/Juniper/jsnapy/files/1785275/jsnapy_rpc_snapshot_20180306.xml.txt)
- Full body of the yml for the test (in my original version, without your suggested changes):
[jsnapydhcptest.yml.txt](https://github.com/Juniper/jsnapy/files/1785293/jsnapydhcptest.yml.txt)
- Complete output of my version of the test [test_output_original.txt](https://github.com/Juniper/jsnapy/files/1785304/test_output_original.txt)
- Complete output of your version of the test [test_output_with_sidhujasminder_changes.txt](https://github.com/Juniper/jsnapy/files/1785308/test_output_with_sidhujasminder_changes.txt)

Please also find attached a flowchart that i hope will do a better job than i did at explaining the testing we are trying to achieve.
![dhcp relay test flowchart](https://user-images.githubusercontent.com/855062/37036432-9592adbe-2147-11e8-911b-3590d5322008.png)

I hope this explains our situation better.

Thanks!

**Comment by sidhujasminder** [comment]
@itsgc looking into it. Thanks for the information.

**Comment by sidhujasminder** [comment]
Hi @itsgc, for your test case please try to use, the operator exists().

```
test_applications:
    - rpc: get-config
    - kwargs:
        filter_xml: configuration/routing-instances
    - iterate:
        xpath: //instance/forwarding-options/dhcp-relay/server-group
        id: ../../../name
        tests:
            - exists: server-group/address/name[text() = '172.17.32.10']
              info: "Test Succeeded!! Something exists for {{id_0}}"
              err: "Test Failed for {{id_0}} !!!"

```
I am getting the following output with this.
```
(env2) jasminder-mbp:env2 jasminder$ jsnapy --snapcheck pre -f main.yml --local -v
**************************** Device: 1.1.1.1 ****************************
Tests Included: test_applications 
*************************RPC is get-config*************************
-----------------------Performing exists Test Operation-----------------------
Test Succeeded!! Something exists for vrf1
Test Failed vrf2 !!!
Test Succeeded!! Something exists for vrf3
Test Failed vrf4 !!!
Test Failed vrf5 !!!
Test Succeeded!! Something exists for vrf6
Test Succeeded!! Something exists for vrf7
Test Succeeded!! Something exists for vrf8
FAIL | All "server-group/address/name[text() = '172.17.32.10']" do not exists at xpath "//instance/forwarding-options/dhcp-relay/server-group" [ 5 matched / 3 failed ]
------------------------------- Final Result!! -------------------------------
test_applications : Failed
Total No of tests passed: 0
Total No of tests failed: 1 
Overall Tests failed!!! 

```

The test case you wrote is also fine, where it is iterating for all the address(under server-group) in that instance. Because of which it is iterating for 26 times, out of which it matched 5 times with your test case.

**Comment by itsgc** [comment]
@sidhujasminder fantastic! this totally works. 

I knew i wasn't using yml properly but i couldn't find an example of providing a value to exists anywhere!

Much appreciated. This can be closed now, thanks for your prompt response!
