### ISSUE TITLE
Question : Password

### ISSUE THREAD

**Issue by anudeep26** [Juniper/jsnapy#304]
How do I make jsnapy prompt for username and password in python script?

**Comment by sidhujasminder** [comment]
If you are using JSNAPy as a python module, We dont support the feature for jsnapy prompt in a python script. 
Using the command line module you get prompts for the same.

**Comment by anudeep26** [comment]
Can you suggest an alternative? Can i keep my username and passwd empty and use pyez to connect to the device?

**Comment by sidhujasminder** [comment]
Yes, you can use the pyez device object in that case.

```
dev_obj = Device(host="1.1.1.1", user="foo", passwd="bar")
dev_obj.open()

snapvalue = js.snapcheck(cfg_file, "pre", local=True, dev=dev_obj)
```

or refer the wiki:
https://github.com/Juniper/jsnapy/wiki/4.-Module

If this resolves your issue you can close this issue :)

**Comment by sidhujasminder** [comment]
This seems to be resolved.
