### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Mierdin** [Juniper/jsnapy#310]
Would be nice to have a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file to quickly onboard new developers. Many open source projects have this in their repo to make things more approachable - and it also allows you to let folks know what you expect from issues, as GH will automatically present this to users if it exists when they try to create one.

**Comment by sidhujasminder** [comment]
Fixed Via #314
