### ISSUE TITLE
unable to build wheel for jsnapy

### ISSUE THREAD

**Issue by panks21** [Juniper/jsnapy#311]
Hi
While doing 'pip install jsnapy' the wheel build for jsnapy fails

``Building wheels for collected packages: jsnapy, configparser, icdiff, future
  Running setup.py bdist_wheel for jsnapy ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8eo_Vk/jsnapy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpXLpkBkpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/jnpr
  copying lib/jnpr/__init__.py -> build/lib.linux-x86_64-2.7/jnpr
  creating build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/xml_comparator.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/check.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/snap.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/notify.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/sqlite_store.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/version.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/sqlite_get.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/jsnapy.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/setup_logging.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/operator.py -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/jsnapy.cfg -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/logging.yml -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  copying lib/jnpr/jsnapy/content.html -> build/lib.linux-x86_64-2.7/jnpr/jsnapy
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting tools/jsnap2py -> build/scripts-2.7
  changing mode of build/scripts-2.7/jsnap2py from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/jnpr
  creating build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/xml_comparator.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/check.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/logging.yml -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/jsnapy.cfg -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/snap.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/content.html -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/notify.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/sqlite_store.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/version.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/__init__.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/sqlite_get.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/jsnapy.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/setup_logging.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/jsnapy/operator.py -> build/bdist.linux-x86_64/wheel/jnpr/jsnapy
  copying build/lib.linux-x86_64-2.7/jnpr/__init__.py -> build/bdist.linux-x86_64/wheel/jnpr
  running install_data
  creating /etc/jsnapy
  creating build/bdist.linux-x86_64/wheel/etc
  creating build/bdist.linux-x86_64/wheel/etc/jsnapy
  copying lib/jnpr/jsnapy/logging.yml -> build/bdist.linux-x86_64/wheel/etc/jsnapy
  copying lib/jnpr/jsnapy/jsnapy.cfg -> build/bdist.linux-x86_64/wheel/etc/jsnapy
  creating build/bdist.linux-x86_64/wheel/var
  creating build/bdist.linux-x86_64/wheel/var/log
  creating build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/info.log -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/debug.log -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/critical.log -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/jsnapy.log -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/errors.log -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  copying logs/__init__.py -> build/bdist.linux-x86_64/wheel/var/log/jsnapy
  running install_egg_info
  running egg_info
  writing requirements to lib/jsnapy.egg-info/requires.txt
  writing lib/jsnapy.egg-info/PKG-INFO
  writing top-level names to lib/jsnapy.egg-info/top_level.txt
  writing dependency_links to lib/jsnapy.egg-info/dependency_links.txt
  writing entry points to lib/jsnapy.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'lib/jsnapy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'lib/jsnapy.egg-info/SOURCES.txt'
  Copying lib/jsnapy.egg-info to build/bdist.linux-x86_64/wheel/jsnapy-1.3.1.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/jsnapy-1.3.1.data
  creating build/bdist.linux-x86_64/wheel/jsnapy-1.3.1.data/scripts
  copying build/scripts-2.7/jsnap2py -> build/bdist.linux-x86_64/wheel/jsnapy-1.3.1.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/jsnapy-1.3.1.data/scripts/jsnap2py to 755
  error: [Errno 2] No such file or directory: '/var/log/jsnapy'

  ----------------------------------------
  Failed building wheel for jsnapy
  Running setup.py clean for jsnapy
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /root/.cache/pip/wheels/a3/61/79/424ef897a2f3b14684a7de5d89e8600b460b89663e6ce9d17c
  Running setup.py bdist_wheel for icdiff ... done
  Stored in directory: /root/.cache/pip/wheels/1a/75/05/83767ed2912cd777575eccf339fab90e3ab7472775da065f8c
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
Successfully built configparser icdiff future
Failed to build jsnapy`

**Comment by sidhujasminder** [comment]
@panks21 Did you try `sudo pip install jsnapy`.
If you dont have sudo permissions, I will recommend you to install and run JSNAPy in a python virtualenv. In virtualenv try installing using the following command- `pip install --no-cache jsnapy`.

**Comment by panks21** [comment]
Hi @sidhujasminder this was done in a docker with root privileges. Do you still think that error was due to sudo permissions??

**Comment by sidhujasminder** [comment]
@panks21 under root privileges everything should work fine. Did you try install it in virtualenv?
I am not able to reproduce the issue.

Check if /var path exists?
Does jsnapy work even after bdist Fail?

I will also try this in a docker, let me see if i am to reproduce it.

**Comment by sidhujasminder** [comment]
@panks21 building the wheel for jsnapy brings out the issue. But i see that jsnapy as in functions fine, its the bdist_wheel that needs some fixes for it. Please correct if i am wrong.
