### ISSUE TITLE
Variable with '-' character triggers an issue

### ISSUE THREAD

**Issue by door7302** [Juniper/jsnapy#323]
### Setup

playbook : 

- name: ETAT ROUTEUR APRES
  hosts:
    - all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    credential:
      host: "{{ ansible_ssh_host }}"
      port: "{{ netconf_port }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"
    isis_issue: []
  tasks:
    - name: "Collecte Post-TP de show isis adjacency"
      juniper_junos_jsnapy:
        provider: "{{ credential }}"
        action: "snap_post"
        test_files: "etat_routeur_templates/isis-adj.yml"
    - name: "Comparaison avant/après show isis adjacency"
      juniper_junos_jsnapy:
        action: "check"
        test_files: "etat_routeur_templates/isis-adj.yml"
      register: checkresult
    - name: "Extraire les adjacences ISIS ayant changé"
      set_fact:
        isis_issue: "{{ isis_issue + [item]}}"
      loop: "{{ alarm }}"
      vars:
        alarm: "{{ checkresult['test_results']['show isis adjacency'][0]['failed'] }}"
      when:
        - checkresult["test_results"]["show isis adjacency"][0]["count"]["fail"] != 0
    - name: "Afficher les adjacences ISIS disparues"
      debug:
        msg: "{{ item.id_missing_post.interface-name }}"   <<<<< HERE THE ISSUE 
      loop: "{{ isis_issue }}"
      when: 
        - checkresult["test_results"]["show isis adjacency"][0]["count"]["fail"] != 0
        - item.id_missing_post is defined

Template jsnapy : 

tests_include:
  - isis_adj

isis_adj:
  - command: show isis adjacency
  - iterate:
      xpath: isis-adjacency
      id: interface-name
      tests:
        - no-diff: adjacency-state
          err: "The ISIS adjacency {{post['interface-name']}} state has changed"

### Steps to Reproduce Issue

lauch the playbook. 
We have this issue : 

TASK [Extraire les adjacences ISIS ayant changé] ****************************************************************************
ok: [ntdib999] => (item={u'id_missing_post': {u'interface-name': u'ae40.0'}})

TASK [Afficher les adjacences ISIS disparues] *******************************************************************************
fatal: [ntdib999]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: Unable to look up a name or access an attribute in template string ({{ item.id_missing_post.interface-name }}).
Make sure your variable name does not contain invalid characters like '-': unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'

### Versions Report

JSNAPy version: 1.3.1

**Comment by dgarros** [comment]
Hey @door7302 
if I understood the issue correctly, I think it's a jinja limitation. 
You need to quote all variables name that contains a `-`
so `"{{ item.id_missing_post.interface-name }}"` should be `"{{ item.id_missing_post['interface-name'] }}"`

**Comment by door7302** [comment]
Hi Damien.

I will try. Thks.

**Comment by sidhujasminder** [comment]
@door7302 does the solution provided by damien works for you?

**Comment by door7302** [comment]
Sorry, I didn't test yet...

**Comment by sidhujasminder** [comment]
closing, reopen if observed again.
