### ISSUE TITLE
python 3.7 and 3.8 support

### ISSUE THREAD

**Issue by vnitinv** [Juniper/jsnapy#348]
### Description of Issue/Question
Plan support for latest python versions

### Setup
(Please provide relevant configs, xml snapshots and related files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant. Error trace would be helpful too)

### Versions Report
(Provided by running `jsnapy --version`. Please also mention python version.)

**Comment by CodeTechies** [comment]
is JSNAPy current release supports pyhon3.8?

**Comment by rahkumar651991** [comment]
@CodeTechies - Yes jsnapy supports python3.8
