### ISSUE TITLE
Testcases to be parsed before hostname to increase performance.

### ISSUE THREAD

**Issue by rahkumar651991** [Juniper/jsnapy#350]
### Description of Issue/Question
In case of multiple devices to be processed, the test-cases are being parsed every time. We can parse the test-cases and store it or pass as an argument. For a large number of devices which will run same test-cases, it will increase the performance.

**Comment by chidanandpujar** [comment]
Fixed via https://github.com/Juniper/jsnapy/pull/351, so closing this issue
