### ISSUE TITLE
test file with mix command and rpc, rpc not evaluated

### ISSUE THREAD

**Issue by CodeTechies** [Juniper/jsnapy#371]
I had a test file below for snap_pre and snap_post with command and RPC, and  RPC not evaluated.

test file: 
         tests_include:
  - test_interface_terse
  - test_version
  - test_rpc_version

# for simple, one test using command
test_interface_terse:
  - command: show interfaces terse

test_version:
  - command: show version
  
test_rpc_version:
  - rpc: get-software-information

Test output:

TASK [Simple Print result] ******************************************************************************************************
ok: [VMX01] => {
    "test_result_3": {
        "action": "check",
        "changed": false,
        "device": "10.10.1.31",
        "failed": false,
        "final_result": "Passed",
        "msg": "Test Passed: Passed 2, Failed 0",
        "passPercentage": 100,
        "pass_percentage": 100,
        "router": "10.10.1.31",
        "test_results": {
            "show interfaces terse": [
                {
                    "diff_on": [],
                    "result": true,
                    "testoperation": "simple-diff"
                }
            ],
            "show version": [
                {
                    "diff_on": [],
                    "result": true,
                    "testoperation": "simple-diff"
                }
            ]
        },
        "total_failed": 0,
        "total_passed": 2,
        "total_tests": 2
    }
}

Environment

[root@localhost testfiles]# ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

[root@localhost testfiles]# ansible-galaxy list
# /root/.ansible/roles
- Juniper.junos, 2.3.0
[WARNING]: - the configured path /usr/share/ansible/roles does not exist.
[WARNING]: - the configured path /etc/ansible/roles does not exist.

[root@localhost testfiles]# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ansible (2.9.6)
bcrypt (3.1.7)
cffi (1.14.0)
colorama (0.4.3)
configparser (4.0.2)
cryptography (2.8)
future (0.18.2)
icdiff (1.9.1)
Jinja2 (2.11.1)
jsnapy (1.3.5.dev0)
junos-eznc (2.3.1)
jxmlease (1.0.1)
lxml (4.5.0)
MarkupSafe (1.1.1)
ncclient (0.6.7)
netaddr (0.7.19)
paramiko (2.7.1)
pip (9.0.3)
pycparser (2.20)
PyNaCl (1.3.0)
pyparsing (2.4.6)
pyserial (3.4)
PyYAML (5.3.1)
scp (0.13.2)
setuptools (39.2.0)
six (1.14.0)
transitions (0.8.0)
yamlordereddictloader (0.4.0)
[root@localhost testfiles]#

**Comment by rahkumar651991** [comment]
hi @CodeTechies , 
I assume you are running jsnapy via ansible module. Please clarify it. 
Could you please tell this few informations which will help us. 
*) the list of roles currently installed. use command - "ansible-galaxy role list"
*) execute the playbook in verbose mode and share the output. 
*) the testcase playbook used for running the jsnapy testcases.

**Comment by CodeTechies** [comment]
I assume you are running jsnapy via ansible module. Please clarify it. >>> Yes

Could you please tell this few informations which will help us.
*) the list of roles currently installed. use command - "ansible-galaxy role list"
   **# /root/.ansible/roles
- Juniper.junos, 2.3.0
[WARNING]: - the configured path /usr/share/ansible/roles does not exist.
[WARNING]: - the configured path /etc/ansible/roles does not exist.**

*) execute the playbook in verbose mode and share the output.
TASK [Simple Take a pre-maintenance snapshot of the interfaces] *****************************************************************
task path: /root/jsnapy/testfiles/jsnapy_ansible_test.yml:102
<10.10.1.31> ESTABLISH LOCAL CONNECTION FOR USER: lab
<10.10.1.31> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770 `" && echo ansible-tmp-1584945031.1363335-189857673949770="` echo /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770 `" ) && sleep 0'
Using module file /root/.ansible/roles/Juniper.junos/library/juniper_junos_jsnapy.py
<10.10.1.31> PUT /root/.ansible/tmp/ansible-local-963321gzrplby/tmpfadklhc7 TO /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770/AnsiballZ_juniper_junos_jsnapy.py
<10.10.1.31> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770/ /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1584945031.1363335-189857673949770/ > /dev/null 2>&1 && sleep 0'
ok: [VMX01] => {
    "action": "snap_pre",
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "snap_pre",
            "attempts": null,
            "baud": null,
            "config_file": null,
            "console": null,
            "cs_passwd": null,
            "cs_user": null,
            "dir": "/root/jsnapy/testfiles",
            "host": "10.10.1.31",
            "level": null,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "ssh_config": null,
            "ssh_private_key_file": null,
            "test_files": [
                "test_diff_simple.yml"
            ],
            "timeout": 30,
            "user": "lab"
        }
    },
    "msg": "The snap_pre action successfully executed."
}

TASK [Simple Take a post-maintenance snapshot of the interfaces] ****************************************************************
task path: /root/jsnapy/testfiles/jsnapy_ansible_test.yml:110
<10.10.1.31> ESTABLISH LOCAL CONNECTION FOR USER: lab
<10.10.1.31> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901 `" && echo ansible-tmp-1584945032.533294-237432044442901="` echo /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901 `" ) && sleep 0'
Using module file /root/.ansible/roles/Juniper.junos/library/juniper_junos_jsnapy.py
<10.10.1.31> PUT /root/.ansible/tmp/ansible-local-963321gzrplby/tmpeg9fnrt_ TO /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901/AnsiballZ_juniper_junos_jsnapy.py
<10.10.1.31> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901/ /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1584945032.533294-237432044442901/ > /dev/null 2>&1 && sleep 0'
ok: [VMX01] => {
    "action": "snap_post",
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "snap_post",
            "attempts": null,
            "baud": null,
            "config_file": null,
            "console": null,
            "cs_passwd": null,
            "cs_user": null,
            "dir": "/root/jsnapy/testfiles",
            "host": "10.10.1.31",
            "level": null,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "ssh_config": null,
            "ssh_private_key_file": null,
            "test_files": [
                "test_diff_simple.yml"
            ],
            "timeout": 30,
            "user": "lab"
        }
    },
    "msg": "The snap_post action successfully executed."
}

TASK [Simple Compare PRE and POST snapshots] ************************************************************************************
task path: /root/jsnapy/testfiles/jsnapy_ansible_test.yml:118
<10.10.1.31> ESTABLISH LOCAL CONNECTION FOR USER: lab
<10.10.1.31> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245 `" && echo ansible-tmp-1584945033.9331014-246963280661245="` echo /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245 `" ) && sleep 0'
Using module file /root/.ansible/roles/Juniper.junos/library/juniper_junos_jsnapy.py
<10.10.1.31> PUT /root/.ansible/tmp/ansible-local-963321gzrplby/tmpm7s_g1hc TO /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245/AnsiballZ_juniper_junos_jsnapy.py
<10.10.1.31> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245/ /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245/AnsiballZ_juniper_junos_jsnapy.py && sleep 0'
<10.10.1.31> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1584945033.9331014-246963280661245/ > /dev/null 2>&1 && sleep 0'
ok: [VMX01] => {
    "action": "check",
    "changed": false,
    "device": "10.10.1.31",
    "final_result": "Passed",
    "invocation": {
        "module_args": {
            "action": "check",
            "attempts": null,
            "baud": null,
            "config_file": null,
            "console": null,
            "cs_passwd": null,
            "cs_user": null,
            "dir": "/root/jsnapy/testfiles",
            "host": "10.10.1.31",
            "level": null,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "ssh_config": null,
            "ssh_private_key_file": null,
            "test_files": [
                "test_diff_simple.yml"
            ],
            "timeout": 30,
            "user": "lab"
        }
    },
    "msg": "Test Passed: Passed 2, Failed 0",
    "passPercentage": 100,
    "pass_percentage": 100,
    "router": "10.10.1.31",
    "test_results": {
        "show interfaces terse": [
            {
                "diff_on": [],
                "result": true,
                "testoperation": "simple-diff"
            }
        ],
        "show version": [
            {
                "diff_on": [],
                "result": true,
                "testoperation": "simple-diff"
            }
        ]
    },
    "total_failed": 0,
    "total_passed": 2,
    "total_tests": 2
}

TASK [Simple Print result] ******************************************************************************************************
task path: /root/jsnapy/testfiles/jsnapy_ansible_test.yml:127
ok: [VMX01] => {
    "test_result_3": {
        "action": "check",
        "changed": false,
        "device": "10.10.1.31",
        "failed": false,
        "final_result": "Passed",
        "msg": "Test Passed: Passed 2, Failed 0",
        "passPercentage": 100,
        "pass_percentage": 100,
        "router": "10.10.1.31",
        "test_results": {
            "show interfaces terse": [
                {
                    "diff_on": [],
                    "result": true,
                    "testoperation": "simple-diff"
                }
            ],
            "show version": [
                {
                    "diff_on": [],
                    "result": true,
                    "testoperation": "simple-diff"
                }
            ]
        },
        "total_failed": 0,
        "total_passed": 2,
        "total_tests": 2
    }
}

TASK [Verify JSNAPy PRE and POST tests passed] **********************************************************************************
task path: /root/jsnapy/testfiles/jsnapy_ansible_test.yml:131
ok: [VMX01] => {
    "changed": false,
    "msg": "All assertions passed"
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************
VMX01                      : ok=16   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

*) the testcase playbook used for running the jsnapy testcases.

  
    - name: Simple Take a pre-maintenance snapshot of the interfaces
      juniper_junos_jsnapy:
        provider: "{{ connection_settings }}"
        action: "snap_pre"
        dir: "~/jsnapy/testfiles"
        test_files: "test_diff_simple.yml"
        logfile: "jsnapy_check_tests.log"
    
    - name: Simple Take a post-maintenance snapshot of the interfaces
      juniper_junos_jsnapy:
        provider: "{{ connection_settings }}"
        action: "snap_post"
        dir: "~/jsnapy/testfiles"
        test_files: "test_diff_simple.yml"
        logfile: "jsnapy_check_tests.log"
    
    - name: Simple Compare PRE and POST snapshots
      juniper_junos_jsnapy:
        provider: "{{ connection_settings }}"
        action: "check"
        dir: "~/jsnapy/testfiles"
        test_files: "test_diff_simple.yml"
        logfile: "jsnapy_check_tests.log"
      register: test_result_3

    - name: "Simple Print result"
      debug:
        var: test_result_3

    - name: Verify JSNAPy PRE and POST tests passed
      assert:
        that:
          - "test_result_3.passPercentage == 100"

**Comment by rahkumar651991** [comment]
Hi @CodeTechies , 

What you have tried is a basic and simple example. If you check your snapshots folder, the snapshot for PRE and POST would have been created for all three cases(2 command and 1 rpc).

Please change your test yaml file to something more relevant for operations like check. I am giving a simple example for just rpc. Should be done similarly for command also.  
```
tests_include:
  - test_interfaces_terse
  - test_version
  - test_rpc_version

test_interfaces_terse:
  - command: show interfaces terse

test_version:
  - command: show version

test_rpc_version:
  - rpc: get-software-information
  - iterate:
      xpath: package-information
      id: './name'
      tests:
        - no-diff: comment
          info: "Test Succeeded!!, comment is <{{post['comment']}}>"
          err: "Test Failed!!!, comment is <{{post['comment']}}>"
```

Kindly try this and revert if it works for you.

**Comment by CodeTechies** [comment]
above test case works,
 does it require to put more details on RPC?

**Comment by rahkumar651991** [comment]
Command and RPC are treated differently in Jsnapy. 
For RPC it needs additional arguments. With rpc, it is fine to use with snap-operation but with operation like check it needs additional details. 
It is advised to have additional details for both commands and rpc to find put the specific difference you need for operations like check.

**Comment by rahkumar651991** [comment]
The issue was resolved. Closing it.
