### ISSUE TITLE
Trouble with use JSNAPy from python for more than one devices

### ISSUE THREAD

**Issue by yurys555** [Juniper/jsnapy#384]
Hello! I have an error with this Python code.  AttributeError: 'SnapAdmin' object has no attribute 'host_list'
What i'm doing wrong?

from jnpr.jsnapy import SnapAdmin
from jnpr.junos import Device

js = SnapAdmin()

config_file = """
hosts:
  - device: jun_sw1
    port: 22
    username: test
    passwd: test
  - device: jun_sw2
    port: 22
    username: test
    passwd: test
tests:
  - test_interfaces.yml
"""

js.snap(config_file, "pre")

Python 3.7.9
jsnapy==1.3.5
junos-eznc==2.5.4

**Comment by will-mcdermott** [comment]
I had the same issue. The following resolved this for me:

+++ b/lib/jnpr/jsnapy/jsnapy.py
@@ -47,6 +47,7 @@ class SnapAdmin:
+        self.host_list = []
@@ -969,8 +970,7 @@ class SnapAdmin:
-                        host_dict[iter] = deepcopy(val.get(hostname))
-                        host_dict[iter]["device"] = hostname
+                        host_dict[iter] = deepcopy(val)

**Comment by yurys555** [comment]
Thanks! It's helped.

**Comment by macbinjo** [comment]
@will-mcdermott Thank you, I was about to get a headache 👍

**Comment by chidanandpujar** [comment]
issue is not reproducible in the latest jsnapy verision              1.3.8.dev0, we will close this issue as fixed.

Please refer the following pass logs.

```
from jnpr.jsnapy import SnapAdmin
from pprint import pprint
from jnpr.junos import Device

js = SnapAdmin()

config_data = """
hosts:
  - device: x.x.x.x
    username : xyz
    passwd: xyz

  - device: x.x.x.x
    username : xyz
    passwd: xyz
tests:
  - test_snmp.yml 
"""

snap = js.snap(config_data, "pre")


python issu_384_mult_dev.py 
Connecting to device x.x.x.x ................
Taking snapshot of RPC: get-configuration
Connecting to device x.x.x.x ................
Taking snapshot of RPC: get-configuration

```
Thanks
Chidanand

**Comment by chidanandpujar** [comment]
issue is not reproducible in the latest jsnapy verision 1.3.8.dev0, we will close this issue as fixed.

Thanks
Chidanand
