### ISSUE TITLE
Fix typos for PRE and POST keys in the node_value_passed of not_exists operator

### ISSUE THREAD

**Issue by quangtamle** [Juniper/jsnapy#410]
### Description of Issue/Question

According to the [code](https://github.com/Juniper/jsnapy/blob/master/lib/jnpr/jsnapy/operator.py#L563): 

PRE and POST keys in the **node_value_passed** dict of **not_exists** operator are capitalized which are not synchronized (should be in small letters like the others)

I wonder whether those capital keys are on purpose or not. If not, can we fix those to small letters for unified format of node_value_passed dict ?

### Setup
(Please provide relevant configs, xml snapshots and related files (Be sure to remove sensitive info).)
No need

### Steps to Reproduce Issue
(Include debug logs if possible and relevant. Error trace would be helpful too)
No need

### Versions Report
(Provided by running `jsnapy --version`. Please also mention python version.)
the current version

**Comment by chidanandpujar** [comment]
Fix is under review https://github.com/Juniper/jsnapy/pull/414

**Comment by chidanandpujar** [comment]
Fixed via #414
