### ISSUE TITLE
Feature Request: Chained Tests

### ISSUE THREAD

**Issue by dmontagner** [Juniper/jsnapy#46]
Type: Feature Request
Name: Chained Tests
Submitter: Diogo Montagner <dmontagner@juniper.net>
Description:

This feature will enable the use of logical operators to build complex test cases.

The feature will also enable the ability to test multiple XML elements in the same test case.

Example of test:

Test Cond1 == TRUE op-AND
   Test Cond2 == TRUE op-AND
      Test CondN == TRUE op-AND
          Then Pass
Else
    Fail

Even better if we could use all logic operator (AND, OR, XOR, NAND, NOR,
NXOR, NOT).

**Comment by eeishaan** [comment]
@dmontagner We are thinking of the following grammar for tests:
 
```
tests:
          - exp
```
where 
_exp_  ->  _catA-op_  _exp_ _exp_  | _catB-op_ _test_cond_ 

_catA-op_  -> _AND_ | _OR_   
_catB-op_  -> _NOT_ | _epsilon_

This grammar translates to the following example in yaml syntax:

```
tests:
- OR:
    - AND:
        - not-equal: last-state,Idle       # element in which test is performed
                err: "Test Failed!! last state is <{{post['last-state']}}>"
                info: "Test succeeded!! last state is not equal to idle, it is: <{{post['last-state']}}>"

        - NOT:
            - all-same: flap-count
                err: "Test Failed!!! flap count are not all same!!, it is <{{post['flap-count']}}> "
                info: "Test Succeeded!! flap count are all same, it is now <{{post['flap-count']}}>!!!"

   - is-equal: flap-count, 0
            err: "Test Failed!!! flap count is not equal to 0, it is: <{{post['flap-count']}}> "
            info: "Test Succeeded!! flap count is equal to <{{post['flap-count']}}> !!"
```

Kindly provide some feedback

**Comment by dmontagner** [comment]
Hi Ishaan,

Hi Ishaan,

If I correct understood the grammar, it will allow unlimited operator recursion, i.e., I can have 3, 4 or more levels of chaining inside one test. Is that correct ?

For example:

> - OR:
>     - AND:
>         - not-equal: last-state,Idle       # element in which test is performed
>                 err: "Test Failed!! last state is <{{post['last-state']}}>"
>                 info: "Test succeeded!! last state is not equal to idle, it is: <{{post['last-state']}}>"
         AND:
>             - not-equal: last-state,Idle       # element in which test is performed
>                     err: "Test Failed!! last state is <{{post['last-state']}}>"
>                     info: "Test succeeded!! last state is not equal to idle, it is: <{{post['last-state']}}>"
<...>

Is the above allowed for the suggested grammar ? (sorry, last time I played with compiler grammars was long long time ago :-)

Another thing I would like to suggest is a XOR operator.

Thanks

Diogo Montagner
Juniper Networks
Mobile: +61 499 075 297
Phone: +61 3 9655 8368 (ext 18368)
dmontagner@juniper.net
http://www.juniper.net

**Comment by eeishaan** [comment]
Yes, the proposed grammar can recursively go to any depth
